[build]
command = ""
publish = "."

[env.production]
name = "beaconoftech"
routes = [
  { pattern = "beaconoftech.com/*", zone_name = "beaconoftech.com" },
  { pattern = "www.beaconoftech.com/*", zone_name = "beaconoftech.com" }
]

[env.preview]
name = "beaconoftech-preview"
